version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/app
    environment:
      APP_ENV: ${APP_ENV:-dev}
      DATABASE_URL: mysql://user:password@database:3306/symfony
    networks:
      - symfony

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony

  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - 3306:3306
    networks:
      - symfony

networks:
  symfony:
    driver: bridge
